name = "maxmin"
license = "MIT"
licenselink = "LICENSE.md"
description = "Maximal Minimalist Hugo theme"
homepage = "."
tags = []
features = []

[author]
  name = "Sam Bacha"
  homepage = "https://sambacha."

pygmentsCodefences = true


[markup]

[markup.highlight]
      codeFences = true
      style = 'emacs'
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      tabWidth = 4
      noClasses = false
