name = "MaxMin"
license = "MIT"
licenselink = "LICENSE.md"
description = "Maximal Minimalist Hugo theme"
homepage = "."
tags = []
features = []

[author]
  name = "Sam Bacha"
  homepage = "https://"

pygmentsCodefences = true


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'emacs'
tabWidth = 4